
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: root
    password: Ritvik@123
#    data: C:\Users\msvvr\Downloads\sportscenter\sportscenter\docker\data.sql
  application:
    name: SportsCenter
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql


  data:
    redis:
      host: localhost
      port: 6379